export const GET_INFOR_ACCOUNT_SUCCESS = "GET_INFOR_ACCOUNT_SUCCESS";
export const GET_INFOR_ACCOUNT_REQUEST = "GET_INFOR_ACCOUNT_REQUEST";
export const GET_INFOR_ACCOUNT_FAILED = "GET_INFOR_ACCOUNT_FAILED";