export const GET_INFOR_MOVIE_LIST_REQUEST = "GET_INFOR_MOVIE_LIST_REQUEST";
export const GET_INFOR_MOVIE_LIST_SUCCESS = "GET_INFOR_MOVIE_LIST_SUCCESS";
export const GET_INFOR_MOVIE_LIST_FAILED = "GET_INFOR_MOVIE_LIST_FAILED";