export const GET_SHOWTIMES_REQUEST = "GET_SHOWTIMES_REQUEST";
export const GET_SHOWTIMES_SUCCESS = "GET_SHOWTIMES_SUCCESS";
export const GET_SHOWTIMES_FAILED = "GET_SHOWTIMES_FAILED";
export const POST_ID_THEATER_CHOOSE = "POST_ID_THEATER_CHOOSE";
export const POST_THEATERGROUP_CHOOSED = "POST_THEATERGROUP_CHOOSED";