export const GET_THEATER_LIST_REQUEST = "GET_THEATER_LIST_REQUEST";
export const GET_THEATER_LIST_SUCCESS = "GET_THEATER_LIST_SUCCESS";
export const GET_THEATER_LIST_FAILED = "GET_THEATER_LIST_FAILED";